services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/coffee-rental
      - PORT=3000
      - HOST=0.0.0.0
    expose:
      - "3000"
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped
    command: ["--wiredTigerCacheSizeGB", "0.25"]

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
