services:
  nginx:
    container_name: coffee-rental-nginx
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network
    expose:
      - 80
    restart: unless-stopped

  app:
    container_name: coffee-rental-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/coffee-rental
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - app-network
    expose:
      - 3000
    restart: unless-stopped

  mongodb:
    container_name: coffee-rental-mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
