services:
  nginx:
    container_name: coffee-rental-nginx
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx
    depends_on:
      app:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "80:80"
    restart: unless-stopped
    mem_limit: 64m
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    container_name: coffee-rental-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/coffee-rental
      - PORT=3000
      - HOST=0.0.0.0
    expose:
      - "3000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      app-network:
        aliases:
          - app
    restart: unless-stopped
    mem_limit: 256m
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    container_name: coffee-rental-mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      app-network:
        aliases:
          - mongodb
    restart: unless-stopped
    mem_limit: 256m
    command: ["--wiredTigerCacheSizeGB", "0.25"]
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    name: coffee-rental-network
    driver: bridge

volumes:
  mongodb_data:
    name: coffee-rental-mongodb-data
    driver: local
  nginx_logs:
    name: coffee-rental-nginx-logs
    driver: local
