services:
  nginx:
    container_name: coffee-rental-nginx
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network
    ports:
      - "80:80"
    restart: unless-stopped
    mem_limit: 64m
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    container_name: coffee-rental-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/coffee-rental
      - PORT=3000
    expose:
      - "3000"
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 256m
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    container_name: coffee-rental-mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 256m
    command: ["--wiredTigerCacheSizeGB", "0.25"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  nginx_logs:
    driver: local
